# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import payloadresponse_pb2 as payloadresponse__pb2


class ImageSimilarityServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.image_similarity = channel.unary_unary(
        '/ImageSimilarityService/image_similarity',
        request_serializer=payloadresponse__pb2.Payload.SerializeToString,
        response_deserializer=payloadresponse__pb2.Response.FromString,
        )


class ImageSimilarityServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def image_similarity(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ImageSimilarityServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'image_similarity': grpc.unary_unary_rpc_method_handler(
          servicer.image_similarity,
          request_deserializer=payloadresponse__pb2.Payload.FromString,
          response_serializer=payloadresponse__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ImageSimilarityService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
